spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle
    driver-class-name: org.postgresql.Driver
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false